name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build WAR
        run: mvn clean package -U -DskipTests

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "target/groupware-0.0.1-SNAPSHOT.war,Dockerfile"
          target: "/home/ubuntu/app"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/app
            docker stop groupware || true
            docker rm groupware || true
            docker rmi groupware || true
            docker builder prune -af || true   # 🔹 빌드 캐시 삭제
            docker build --no-cache -t groupware .
            docker run -d --name groupware -p 8080:8080 groupware
